### PR TITLE
Storybook v7 compatibility - and dependency updates

### PR DESCRIPTION
**Pull request by meza**
I've made the changes necessary for this to work with Storybook v7

It also contains the suggested fix from #15 

> **Note** I've published the package as @meza/storybook-react-i18next to test it and to use it until this gets merged.

I've also ran prettier it seems like it hasn't been applied in a while.

### CODE REVIEW

**Comment by stevensacks** [comment]
Thanks for this! I will review. If it isn’t backwards compatible with Storybook 6, I think we need to bump the major version to 2.

**Comment by JReinhold** [comment]
Hey @meza and @stevensacks, Storybook v7.0.0 is out! It's only on the `next` tag for now, but it's still targetable with the `^7.0.0` semver range, so you should be able to develop against it with no dependency issues.

If you hit any issues with v7, we've written a migration guide for addon authors [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#specific-instructions-for-addon-creators) and [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040).

You're also free to reach out to us in the #prerelease channel on our [Discord Server](https://discord.gg/storybook) and we'll happily help you out!

cc @ndelangen

**Comment by stevensacks** [comment]
I’ll be merging this in soon. Just working through a couple of issues.

**Comment by dohomi** [comment]
great looking forward for this to be released! Thanks for your work on this addon

**Review by ndelangen — APPROVED** [review]

**Comment by Woodii1998** [comment]
I'm looking forward to the compatibility with storybook 7! When is the official release expected?

**Comment by stevensacks** [comment]
I fixed this more completely in a different PR.

**Pull request closed without merging**
